status code response

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -78,7 +78,7 @@ jobs:
           # Create a github release
           # https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
           REQUEST_DATA=$(echo "$PAYLOAD_TEMPLATE" | jq -c)
-          echo $REQUEST_DATA | curl \
+          RESPONSE=$(echo $REQUEST_DATA | curl \
             --silent \
             --location \
             --request POST \
@@ -86,5 +86,18 @@ jobs:
             --header "Authorization: Bearer $GITHUB_TOKEN" \
             --header "X-GitHub-Api-Version: 2022-11-28" \
             --data @- \
+            --write-out "%{http_code}" \
             https://api.github.com/repos/$GITHUB_REPOSITORY/releases
+          )
 
+          # Extract the response status code and body
+          RESPONSE_CODE=${RESPONSE: -3}
+          RESPONSE_BODY=${RESPONSE//$RESPONSE_CODE/}
+
+          if [ "$RESPONSE_CODE" -ne  201 ]; then
+            ERROR_MESSAGE=$(echo "$RESPONSE_BODY" | jq '.message')
+            echo "HTTP $RESPONSE_CODE - $ERROR_MESSAGE"
+            exit 1
+          fi
+
+          echo "Release ($REF_NAME) successfully created"
